version: "3"
services:
  socks5lb:
    build:
      context: .
    image: ghcr.io/mingcheng/socks5lb
    environment:
      CHECK_INTERVAL: 60s
      CHECK_TIMEOUT: 10s
      DEBUG: "true"
    ports:
      - 1080:1080
    volumes:
      - ./socks5lb.yml:/etc/socks5lb.yml:ro
    restart: unless-stopped
